# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "ehci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/619b125b-20c3-48da-be84-68802ba45b34";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8978-7AE6";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # 将两个交换设备合并到一个列表里
  swapDevices = [ 
    # 这是你原本的物理交换分区
    { device = "/dev/disk/by-uuid/b1a8ea8b-5981-452a-b2ad-dabd0e2f7138"; } 
    
    # 这是你新增的 16GB 交换文件
    { device = "/var/lib/swapfile"; size = 16384; } 
  ];
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
